# Buổi 02 – Phân tích dữ liệu bán hàng (Sales Data Sample)

**Bộ dữ liệu:** `sales_data_sample.xlsx` – dữ liệu bán hàng của công ty đa quốc gia ABC.

**Mô tả các cột:**
| Cột | Ý nghĩa |
|---|---|
| ORDERNUMBER | Mã hóa đơn |
| QUANTITYORDERED | Số lượng sản phẩm đặt hàng |
| ORDERLINENUMBER | Dòng thông tin mua sản phẩm trên hóa đơn |
| SALES | Giá trị đặt hàng |
| ORDERDATE | Ngày đặt hàng |
| STATUS | Trạng thái giao hàng |
| COUNTRY | Địa điểm đặt hàng |
| DEALSIZE | Phân loại kích thước đơn hàng (Small/Medium/Large) |
| Discount | Giảm giá (%) |
| Profit | Lợi nhuận |

---
## Phần 1: Nhập và khám phá dữ liệu tổng quan

**Câu 1.** Đọc dữ liệu từ file `sales_data_sample.xlsx` vào DataFrame tên `df`. Hiển thị 5 dòng đầu và 5 dòng cuối của dữ liệu.

In [2]:
import pandas as pd
df = pd.read_excel("sales_data_sample.xlsx")
display(df.head(5))
display(df.tail(5))

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit
0,10107,30,2,2871.00,2003-02-24,Shipped,USA,Small,0.00,41.9136
1,10121,34,5,2765.90,2003-05-07,Shipped,France,Small,0.00,219.5820
2,10134,41,2,3884.34,2003-07-01,Shipped,France,Medium,0.00,6.8714
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.20,2.5164

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit
2818,10350,20,15,2244.40,2004-12-02,Shipped,Spain,Small,0.0,315.7404
2819,10373,29,1,3978.51,2005-01-31,Shipped,Finland,Medium,0.2,2.3520
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.2,7.4694
2821,10397,34,1,2116.16,2005-03-28,Shipped,France,Small,0.2,22.6782
2822,10414,47,9,3079.44,2005-05-06,On Hold,USA,Medium,0.2,0.5580

**Câu 2.** Cho biết DataFrame có bao nhiêu dòng, bao nhiêu cột? Kiểu dữ liệu (dtype) của từng cột là gì?

In [13]:
df.shape
df.dtypes
print(f"So dong: {len(df)}")
print("so dong: ", len(df))
df.columns.tolist()

for i in df.columns.tolist():
    print(i)

So dong: 2823
so dong:  2823
ORDERNUMBER
QUANTITYORDERED
ORDERLINENUMBER
SALES
ORDERDATE
STATUS
COUNTRY
DEALSIZE
Discount
Profit

In [14]:
", ".join(df.columns.tolist())

'ORDERNUMBER, QUANTITYORDERED, ORDERLINENUMBER, SALES, ORDERDATE, STATUS, COUNTRY, DEALSIZE, Discount, Profit'

In [15]:
df.dtypes

ORDERNUMBER                 int64
QUANTITYORDERED             int64
ORDERLINENUMBER             int64
SALES                     float64
ORDERDATE          datetime64[us]
STATUS                        str
COUNTRY                       str
DEALSIZE                      str
Discount                  float64
Profit                    float64
dtype: object

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ORDERNUMBER      2823 non-null   int64
 1   QUANTITYORDERED  2823 non-null   int64
 2   ORDERLINENUMBER  2823 non-null   int64
 3   SALES            2823 non-null   float64
 4   ORDERDATE        2823 non-null   datetime64[us]
 5   STATUS           2823 non-null   str
 6   COUNTRY          2823 non-null   str
 7   DEALSIZE         2823 non-null   str
 8   Discount         2823 non-null   float64
 9   Profit           2823 non-null   float64
dtypes: datetime64[us](1), float64(3), int64(3), str(3)
memory usage: 220.7 KB

In [17]:
display(df.head(10))
display(df.tail(10))

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit
0,10107,30,2,2871.00,2003-02-24,Shipped,USA,Small,0.00,41.9136
1,10121,34,5,2765.90,2003-05-07,Shipped,France,Small,0.00,219.5820
2,10134,41,2,3884.34,2003-07-01,Shipped,France,Medium,0.00,6.8714
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.20,2.5164
5,10168,36,1,3479.76,2003-10-28,Shipped,USA,Medium,0.00,14.1694
6,10180,29,9,2497.77,2003-11-11,Shipped,France,Small,0.00,1.9656
7,10188,48,1,5512.32,2003-11-18,Shipped,Norway,Medium,0.20,90.7152
8,10201,22,2,2168.54,2003-12-01,Shipped,USA,Small,0.20,5.7825
9,10211,41,14,4708.44,2004-01-15,Shipped,France,Medium,0.00,34.4700

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit
2813,10293,32,1,1921.92,2004-09-09,Shipped,Italy,Small,0.0,229.9908
2814,10306,35,6,2082.85,2004-10-14,Shipped,UK,Small,0.0,111.1035
2815,10315,40,5,2227.60,2004-10-29,Shipped,France,Small,0.0,51.5700
2816,10327,37,4,3209.38,2004-11-10,Resolved,Denmark,Medium,0.0,15.1850
2817,10337,42,5,4080.72,2004-11-21,Shipped,USA,Medium,0.0,27.3592
2818,10350,20,15,2244.40,2004-12-02,Shipped,Spain,Small,0.0,315.7404
2819,10373,29,1,3978.51,2005-01-31,Shipped,Finland,Medium,0.2,2.3520
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.2,7.4694
2821,10397,34,1,2116.16,2005-03-28,Shipped,France,Small,0.2,22.6782
2822,10414,47,9,3079.44,2005-05-06,On Hold,USA,Medium,0.2,0.5580

In [18]:
df.isnull().sum()

ORDERNUMBER        0
QUANTITYORDERED    0
ORDERLINENUMBER    0
SALES              0
ORDERDATE          0
STATUS             0
COUNTRY            0
DEALSIZE           0
Discount           0
Profit             0
dtype: int64

**Câu 3.** Kiểm tra xem dữ liệu có giá trị thiếu (missing values) ở cột nào không? Có dòng nào bị trùng lặp hoàn toàn (duplicate) không?

In [4]:
df.isnull().sum()
print(df.duplicated())
df.drop_duplicates(inplace= True)

0       False
1       False
2       False
3       False
4       False
        ...
2818    False
2819    False
2820    False
2821    False
2822    False
Length: 2823, dtype: bool

In [21]:
df.duplicated().sum()

np.int64(0)

**Câu 4.** Sử dụng `describe()` để xem thống kê mô tả (min, max, mean, std...) cho các cột số: `QUANTITYORDERED`, `SALES`, `Discount`, `Profit`. Nhận xét ngắn gọn về khoảng giá trị của `Discount` và `Profit`.

**Câu 5.** Dữ liệu có bao nhiêu quốc gia (COUNTRY) khác nhau? Liệt kê tên các quốc gia đó. Có bao nhiêu giá trị khác nhau trong cột `STATUS` và `DEALSIZE`? Đó là những giá trị nào?

In [37]:
df["COUNTRY"].unique() #khong trung lap

df[['COUNTRY', 'STATUS', "DEALSIZE"]]

      COUNTRY    STATUS DEALSIZE
0         USA   Shipped    Small
1      France   Shipped    Small
2      France   Shipped   Medium
3         USA   Shipped   Medium
4         USA   Shipped   Medium
...       ...       ...      ...
2818    Spain   Shipped    Small
2819  Finland   Shipped   Medium
2820    Spain  Resolved   Medium
2821   France   Shipped    Small
2822      USA   On Hold   Medium

[2823 rows x 3 columns]

In [38]:
df["COUNTRY"].value_counts()

COUNTRY
USA            1004
Spain           342
France          314
Australia       185
UK              144
Italy           113
Finland          92
Norway           85
Singapore        79
Canada           70
Denmark          63
Germany          62
Sweden           57
Austria          55
Japan            52
Belgium          33
Switzerland      31
Philippines      26
Ireland          16
Name: count, dtype: int64

In [40]:
df["COUNTRY"].nunique()

19

In [43]:
sl = 0
for i in df["COUNTRY"].unique():
    sl=sl+1
sl

19

---
## Phần 2: Lọc và sắp xếp dữ liệu

**Câu 6.** Lọc ra các đơn hàng có `SALES` lớn hơn 5000. Có bao nhiêu đơn hàng thỏa điều kiện này?

In [49]:

df[(df["SALES"] > 5000) & (df["COUNTRY"] == "USA")]

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit,ORDER_YEAR,ORDER_MONTH,ORDER_QUARTER,PROFIT_MARGIN,NET_SALES
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.2,2.5164,2003,10,4,0.000483,4164.216
29,10140,37,11,7374.10,2003-07-24,Shipped,USA,Large,0.2,15.5250,2003,7,3,0.002105,5899.280
33,10183,23,8,5372.57,2003-11-13,Shipped,USA,Medium,0.2,3.5460,2003,11,4,0.000660,4298.056
36,10215,35,3,6075.30,2004-01-29,Shipped,USA,Medium,0.6,-147.9630,2004,1,1,-0.024355,2430.120
37,10228,29,2,6463.23,2004-03-10,Shipped,USA,Medium,0.2,35.4150,2004,3,1,0.005479,5170.584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2651,10263,47,9,5465.16,2004-06-28,Shipped,USA,Medium,0.2,3.5022,2004,6,2,0.000641,4372.128
2653,10285,45,13,5392.80,2004-08-27,Shipped,USA,Medium,0.0,80.7912,2004,8,3,0.014981,5392.800
2656,10318,50,8,7119.00,2004-11-02,Shipped,USA,Large,0.0,65.4350,2004,11,4,0.009192,7119.000
2662,10388,50,3,7154.50,2005-03-03,Shipped,USA,Large,0.0,4.2048,2005,3,1,0.000588,7154.500
2689,10401,77,9,7084.00,2005-04-03,On Hold,USA,Large,0.2,1.6400,2005,4,2,0.000232,5667.200

**Câu 7.** Lọc ra các đơn hàng thuộc quốc gia `USA` và có `DEALSIZE` là `Large`. Sắp xếp kết quả theo `SALES` giảm dần và hiển thị 10 dòng đầu tiên.

In [52]:
df[(df['COUNTRY'] == "USA") & (df["DEALSIZE"] == "Large")]

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit,ORDER_YEAR,ORDER_MONTH,ORDER_QUARTER,PROFIT_MARGIN,NET_SALES
29,10140,37,11,7374.10,2003-07-24,Shipped,USA,Large,0.2,15.5250,2003,7,3,0.002105,5899.280
44,10312,48,3,11623.70,2004-10-21,Shipped,USA,Large,0.0,19.7714,2004,10,4,0.001701,11623.700
50,10381,36,3,8254.80,2005-02-17,Shipped,USA,Large,0.0,35.3346,2005,2,1,0.004280,8254.800
88,10201,49,4,8065.89,2003-12-01,Shipped,USA,Large,0.2,13.8572,2003,12,4,0.001718,6452.712
91,10237,39,9,7023.90,2004-04-05,Shipped,USA,Large,0.0,3.1104,2004,4,2,0.000443,7023.900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2505,10388,46,2,10066.60,2005-03-03,Shipped,USA,Large,0.0,327.5060,2005,3,1,0.032534,10066.600
2586,10401,85,10,7543.75,2005-04-03,On Hold,USA,Large,0.0,67.1139,2005,4,2,0.008897,7543.750
2656,10318,50,8,7119.00,2004-11-02,Shipped,USA,Large,0.0,65.4350,2004,11,4,0.009192,7119.000
2662,10388,50,3,7154.50,2005-03-03,Shipped,USA,Large,0.0,4.2048,2005,3,1,0.000588,7154.500
2689,10401,77,9,7084.00,2005-04-03,On Hold,USA,Large,0.2,1.6400,2005,4,2,0.000232,5667.200

**Câu 8.** Lọc ra các đơn hàng có `Profit` âm (lỗ). Các đơn hàng này thường rơi vào `STATUS` nào? `DEALSIZE` nào? (Gợi ý: dùng `value_counts()`)

In [61]:
df_Profit = df[df["Profit"] < 0]
df_Profit["STATUS"].unique()
df_Profit[["STATUS", "DEALSIZE"]].value_counts()

STATUS      DEALSIZE
Shipped     Medium      220
            Small       205
            Large        29
Cancelled   Small         8
In Process  Small         7
            Medium        6
Cancelled   Medium        6
Resolved    Medium        6
On Hold     Small         5
            Medium        3
            Large         2
Disputed    Small         2
            Large         1
In Process  Large         1
Resolved    Small         1
Name: count, dtype: int64

**Câu 9.** Lọc ra các đơn hàng có mức giảm giá (`Discount`) từ 0.3 trở lên. Doanh số (`SALES`) trung bình của nhóm này là bao nhiêu, so với doanh số trung bình toàn bộ dữ liệu?

---
## Phần 3: Tạo cột mới và biến đổi dữ liệu

**Câu 10.** Từ cột `ORDERDATE`, tạo thêm 3 cột mới: `ORDER_YEAR`, `ORDER_MONTH`, `ORDER_QUARTER` chứa năm, tháng, quý của ngày đặt hàng.

In [23]:
df['ORDERDATE']

0      2003-02-24
1      2003-05-07
2      2003-07-01
3      2003-08-25
4      2003-10-10
          ...
2818   2004-12-02
2819   2005-01-31
2820   2005-03-01
2821   2005-03-28
2822   2005-05-06
Name: ORDERDATE, Length: 2823, dtype: datetime64[us]

In [29]:

df.ORDERDATE.dt.year

df['ORDER_YEAR'] = df.ORDERDATE.dt.year
df
df['ORDER_MONTH'] = df.ORDERDATE.dt.month
df
df['ORDER_QUARTER'] = df.ORDERDATE.dt.quarter
df

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit,ORDER_YEAR,ORDER_MONTH,ORDER_QUARTER
0,10107,30,2,2871.00,2003-02-24,Shipped,USA,Small,0.00,41.9136,2003,2,1
1,10121,34,5,2765.90,2003-05-07,Shipped,France,Small,0.00,219.5820,2003,5,2
2,10134,41,2,3884.34,2003-07-01,Shipped,France,Medium,0.00,6.8714,2003,7,3
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310,2003,8,3
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.20,2.5164,2003,10,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,15,2244.40,2004-12-02,Shipped,Spain,Small,0.00,315.7404,2004,12,4
2819,10373,29,1,3978.51,2005-01-31,Shipped,Finland,Medium,0.20,2.3520,2005,1,1
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.20,7.4694,2005,3,1
2821,10397,34,1,2116.16,2005-03-28,Shipped,France,Small,0.20,22.6782,2005,3,1
2822,10414,47,9,3079.44,2005-05-06,On Hold,USA,Medium,0.20,0.5580,2005,5,2

**Câu 11.** Tạo cột mới `PROFIT_MARGIN` = `Profit` / `SALES` (tỷ suất lợi nhuận). Đơn hàng nào có tỷ suất lợi nhuận cao nhất? Thấp nhất?

In [30]:
df["PROFIT_MARGIN"] = df["Profit"] / df["SALES"]
df

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit,ORDER_YEAR,ORDER_MONTH,ORDER_QUARTER,PROFIT_MARGIN
0,10107,30,2,2871.00,2003-02-24,Shipped,USA,Small,0.00,41.9136,2003,2,1,0.014599
1,10121,34,5,2765.90,2003-05-07,Shipped,France,Small,0.00,219.5820,2003,5,2,0.079389
2,10134,41,2,3884.34,2003-07-01,Shipped,France,Medium,0.00,6.8714,2003,7,3,0.001769
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310,2003,8,3,-0.102232
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.20,2.5164,2003,10,4,0.000483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,15,2244.40,2004-12-02,Shipped,Spain,Small,0.00,315.7404,2004,12,4,0.140679
2819,10373,29,1,3978.51,2005-01-31,Shipped,Finland,Medium,0.20,2.3520,2005,1,1,0.000591
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.20,7.4694,2005,3,1,0.001379
2821,10397,34,1,2116.16,2005-03-28,Shipped,France,Small,0.20,22.6782,2005,3,1,0.010717
2822,10414,47,9,3079.44,2005-05-06,On Hold,USA,Medium,0.20,0.5580,2005,5,2,0.000181

**Câu 12.** Tạo cột `NET_SALES` = `SALES` * (1 - `Discount`) thể hiện doanh số sau khi trừ giảm giá. So sánh tổng `SALES` và tổng `NET_SALES` của toàn bộ dữ liệu.

In [32]:
df["NET_SALES"] = df["SALES"] * (1 - df["Discount"])
df

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit,ORDER_YEAR,ORDER_MONTH,ORDER_QUARTER,PROFIT_MARGIN,NET_SALES
0,10107,30,2,2871.00,2003-02-24,Shipped,USA,Small,0.00,41.9136,2003,2,1,0.014599,2871.000
1,10121,34,5,2765.90,2003-05-07,Shipped,France,Small,0.00,219.5820,2003,5,2,0.079389,2765.900
2,10134,41,2,3884.34,2003-07-01,Shipped,France,Medium,0.00,6.8714,2003,7,3,0.001769,3884.340
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310,2003,8,3,-0.102232,2060.685
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.20,2.5164,2003,10,4,0.000483,4164.216
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,15,2244.40,2004-12-02,Shipped,Spain,Small,0.00,315.7404,2004,12,4,0.140679,2244.400
2819,10373,29,1,3978.51,2005-01-31,Shipped,Finland,Medium,0.20,2.3520,2005,1,1,0.000591,3182.808
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.20,7.4694,2005,3,1,0.001379,4334.056
2821,10397,34,1,2116.16,2005-03-28,Shipped,France,Small,0.20,22.6782,2005,3,1,0.010717,1692.928
2822,10414,47,9,3079.44,2005-05-06,On Hold,USA,Medium,0.20,0.5580,2005,5,2,0.000181,2463.552

---
## Phần 4: Nhóm dữ liệu (Groupby) và tổng hợp

**Câu 13.** Tính tổng `SALES` và tổng `Profit` theo từng `COUNTRY`. Sắp xếp giảm dần theo tổng `SALES` và cho biết Top 5 quốc gia có doanh số cao nhất.

In [71]:
df.groupby('COUNTRY')["SALES"].sum()

df.groupby(by='COUNTRY')[['SALES', 'Profit']].sum().head(5)

              SALES     Profit
COUNTRY
Australia  97561.04 -1574.1764
Austria    31279.51  -813.6460
Belgium    16731.67  -380.9397
Canada     46335.15 -1602.9112
Denmark    52618.46  -659.2730

**Câu 14.** Tính `SALES` trung bình và `Profit` trung bình theo từng nhóm `DEALSIZE`. Nhận xét: nhóm `Large` có thực sự mang lại lợi nhuận trung bình cao nhất không?

In [72]:
df.groupby('DEALSIZE')[['Profit', 'SALES']].mean()

              Profit        SALES
DEALSIZE
Large    -151.402718  8439.574545
Medium    -85.333608  4400.337676
Small     -93.275798  2103.408947

**Câu 15.** Tính số lượng đơn hàng (đếm số `ORDERNUMBER` duy nhất) theo từng `STATUS`. Tỷ lệ đơn hàng bị `Cancelled` hoặc `Disputed` chiếm bao nhiêu % tổng số đơn hàng?

**Câu 16.** Sử dụng `pivot_table` để tạo bảng tổng hợp tổng `SALES` theo `COUNTRY` (hàng) và `DEALSIZE` (cột).

**Câu 17.** Theo `ORDER_YEAR` đã tạo ở Câu 10, tính tổng doanh số (`SALES`) theo từng năm. Doanh số năm nào cao nhất? Lưu ý gì về dữ liệu năm 2005 (dữ liệu có đủ 12 tháng không)?

---
## Phần 6: Câu hỏi tổng hợp / thảo luận

**Câu 22.** Từ những phân tích trên, hãy viết một đoạn nhận xét ngắn (5–7 dòng) về:
- Quốc gia nào đang mang lại doanh số/lợi nhuận tốt nhất cho công ty ABC?
- Nhóm `DEALSIZE` nào hiệu quả nhất?
- Có rủi ro nào đáng lưu ý (ví dụ: đơn hàng lỗ, tỷ lệ hủy/tranh chấp cao) không?
- Đề xuất 1–2 hành động công ty nên cân nhắc.